services:
  mongodb:
    image: 'mongo:8.0.3'
    environment:
      - 'MONGO_INITDB_DATABASE=sfg'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    ports:
      - '27017:27017'
    expose:
      - 27017
  auth-server:
    container_name: auth-server
    image: domboeckli/spring-6-auth-server:0.0.1-SNAPSHOT
    ports:
      - "9000:9000"
    expose:
      - 9000
    environment:
      SPRING_SECURITY_OAUTH2_AUTHORIZATION_SERVER_ISSUER: http://auth-server:9000
  reactive-mongo:
    container_name: reactive-mongo
    image: domboeckli/spring-6-reactive-mongo:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    expose:
      - 8083
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9000
      SERVER_PORT: 8083
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/sfg
      SPRING_DATA_MONGODB_DATABASE: sfg
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: secret
    depends_on:
      mongodb:
        condition: service_started
        required: true       
      auth-server:
        condition: service_started
        required: true 
  gateway:
    container_name: gateway
    image: domboeckli/spring-6-gateway:0.0.1-SNAPSHOT
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9000
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: reactive_mongo_route
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://reactive-mongo:8083
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/api/v3/**
      
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: auth_route
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://auth-server:9000
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path=/oauth2/**
    depends_on:
      auth-server:
        condition: service_started
        required: true
      reactive-mongo:
        condition: service_started
        required: true      
