global:
  timezone: Europe/Zurich
  timezonePath: /etc/localtime
  springDebug: false
  namespace: spring-6-reactive-web-client

replicaCount: 1

image:
  # Those values are set by Maven filtering
  # and will be replaced with a valid version number during the build process.
  registry: @docker.repo@
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8087
  targetPort: 8087
  nodePort: 30087

externalAccess:
  host: "localhost"
  protocol: "http"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

mongodb:
  enabled: true

  port: 27017
  targetPort: 27017
  nodePort: 30017

  serviceFQDN:

authServer:
  enabled: true

  port: 9000
  targetPort: 9000
  nodePort: 30900

  serviceFQDN:

reactiveMongo:
  enabled: true

  port: 8083
  targetPort: 8083
  nodePort: 30083

  serviceFQDN:

ingress:
  enabled: false

# Section for overriding values in subcharts defined in the Chart.yaml

spring-6-auth-server:
  spring:
    issuer:
      uri: "http://spring-6-reactive-web-client-spring-6-auth-server.spring-6-reactive-web-client.svc.cluster.local:9000"

spring-6-reactive-mongo:
  authServer:
    enabled: false
    serviceFQDN: "spring-6-reactive-web-client-spring-6-auth-server.spring-6-reactive-web-client.svc.cluster.local"
  mongodb:
    enabled: false
    # here we use the shortenend name we have defined below
    serviceFQDN: "spring-6-reactive-web-client-mongodb.spring-6-reactive-web-client.svc.cluster.local"

# we need to shorten the name and fullname to avoid a random shortenend name by helm
spring-6-reactive-mongo-mongodb:
  nameOverride: "mongodb"
  fullnameOverride: "spring-6-reactive-web-client-mongodb"
