server:
  port : 8081
  
logging:
  level:
    org.zalando.logbook: TRACE  

spring:
  application:
    name: spring-6-reactive-web-client  
  
  security:
    oauth2:
      client:
        registration:
          springauth:
            client-name: springauth
            client-id: messaging-client
            client-secret: secret
            scope[0]: message.read
            scope[1]: message.write
            authorization-grant-type: client_credentials   
        provider:
          springauth:
            token-uri: http://localhost:9000/oauth2/token
              
      
        

          
          
        
          

webclient:
  rooturl: http://localhost:8080
