### this retrieves the bearer token. use the token in the request below
POST http://localhost:{{auth-server-prt}}/oauth2/token
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=message.read message.write

### this retrieves the bearer token via gateway. use the token in the request below
POST http://localhost:{{auth-server-prt}}/oauth2/token
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=message.read message.write

###
GET http://localhost:{{auth-server-prt}}/actuator/health/readiness
Accept: application/json


