### List Beers
GET http://localhost:8083/api/v3/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiI0NzYxMDdmMy1jMzQzLTRjNzUtYmI0Ni03MDdiODIyYWI3NjUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczNTU3MzY5MywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzM1NTc0MjkzLCJpYXQiOjE3MzU1NzM2OTMsImp0aSI6ImM0YTEzMjdmLTZjZjYtNDk4Ny04NzFiLWYyZTlkMmI5YTczNiJ9.Kx21FKdU8LGC7muXYKeEbrFKiuwj3DRgLy23i6kQy0Y9xEBJzT2D5GSFEw0Mgtc4bVCXDOzrKJH9lNTc3ffPNhmfvAh-km7UYwzVNjsePAz6HZC2CRWdGilr9KaynBrqar_8iK6Q_N0Tpbi4JZFbHTNhuSsIzIAtvPuWSPSEpdu3FfE0PwLhGiGw7YJNocX9iwXq3yhxmO54qgGu1zNI1NXAjN3oBakomgHOp3HiUwcIGIdbJ9QehZqfarP848aQ8Km3S3W2_wyk_v8h9LKak3XjXHRsEpLfsOUmHOVNpRTcKpImUlvbGHKjh2J9EqhgzKMUMuo3CVT0URKMreQaoQ

Content-Type: application/json

### Get Beer by ID
GET http://localhost:8083/api/v3/beer/6746d967f74ca306eaa56db3
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

### Create Beer
POST http://localhost:8083/api/v3/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "presidente",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Create Beer returns BAD REQUEST, beerName is to short
POST http://localhost:8083/api/v3/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "p",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Update Beer by ID
PUT http://localhost:8083/api/v3/beer/673b82a22082c509d439c02d
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "presidenteEdited",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Update Beer by ID returns BAD REQUEST, beerStyle is empty
PUT http://localhost:8083/api/v3/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "presidenteEdited",
    "beerStyle": "",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Patch Beer by ID
PUT http://localhost:8083/api/v3/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "presidentePatched",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Patch Beer by ID. Beername is missing
PUT http://localhost:8083/api/v3/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Delete Beer by ID
DELETE http://localhost:8083/api/v3/beer/6746d967f74ca306eaa56db0
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
