### List Beers directly
GET http://localhost:8083/api/v3/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiIyM2FjM2E5NC1jNjVhLTQyNDktYTJlZS1kODkwOTY3MmExZjEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczNTkwMTE2OSwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vYXV0aC1zZXJ2ZXI6OTAwMCIsImV4cCI6MTczNTkwMTc2OSwiaWF0IjoxNzM1OTAxMTY5LCJqdGkiOiJhOWFkZGFiNi1hZTQzLTRjOGMtOWEzYi1iZjRjNjYxZjhjNGYifQ.azibQ6P_Mx6gfbGqKaxpgXl9kxoQ_ilxnA7KplJqbnbXQTVbGxsXYiRd8T-p9MFlCEuodpyGT9cdGg0KvxiRINUVo6Ig5G3qOEBh5x8k2dLJ6RBaryaJWbUQ9dpXht_Ro7lBGyNbP_DXma3fVMI_qgU2rMSwS1B_-KmJctbkJjpArJSbj1NJCYeuXdFJlo9_QK-rTs5DIeYFoKLegVWW3Y6YBcEovcYNWe4d6PAXcvfZH5FM5R5SyLKeq1rCdmeHD0UZW8Mh0mqF15cgb7k__ysEvNIfmvXLAQLF20s3gYipu5fJiY-V3FxahXTBPfWIOC2ErtW9ZUPDiSmTQgEBjQ

Content-Type: application/json

### List Beers via gateway. retrieve bearer token via gateway
GET http://localhost:8080/api/v3/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiIyM2FjM2E5NC1jNjVhLTQyNDktYTJlZS1kODkwOTY3MmExZjEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczNTkwMTIyMCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vYXV0aC1zZXJ2ZXI6OTAwMCIsImV4cCI6MTczNTkwMTgyMCwiaWF0IjoxNzM1OTAxMjIwLCJqdGkiOiJkMWY0NWNjOC04ZjdkLTQ1NDAtYWE5MS02NDc5NTdkMjkwNWUifQ.vSE3RdsXQQ_5vhQfcmcc5MaSZ7a-5y7e9gO_43TLBXtd6cwCSeoKQ75FUaIocnuwXSc0CJQ-8MJVfS4vjwpbATtpk7I7JN9bGPll_u626Y26ejAf3n0G5db8XQ42RjO_7v3Eqk83edMCV1ZTOLOpVHRpDYKLMfLwrHDiLBhlllTSuCndc3v4riphKiL17M3ogT6jT11U6zmeg-fuwZru3qwBlt2nsJnO3FFUPEUNBJC1Vc5Ffv9qVJuJbfnQAF7QB6uOFVxwKFsGqxbImDHN9xCrOk3yEMMYkcLMzVP9WCxRVCZIBHitJ-ai-kXaSTU7XAxL5_kDZsacRkiY6qJDag

Content-Type: application/json

### Get Beer by ID
GET http://localhost:8083/api/v3/beer/6746d967f74ca306eaa56db3
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

### Create Beer
POST http://localhost:8083/api/v3/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "presidente",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Create Beer returns BAD REQUEST, beerName is to short
POST http://localhost:8083/api/v3/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "p",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Update Beer by ID
PUT http://localhost:8083/api/v3/beer/673b82a22082c509d439c02d
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "presidenteEdited",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Update Beer by ID returns BAD REQUEST, beerStyle is empty
PUT http://localhost:8083/api/v3/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "presidenteEdited",
    "beerStyle": "",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Patch Beer by ID
PUT http://localhost:8083/api/v3/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerName": "presidentePatched",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Patch Beer by ID. Beername is missing
PUT http://localhost:8083/api/v3/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
Content-Type: application/json

{
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Delete Beer by ID
DELETE http://localhost:8083/api/v3/beer/6746d967f74ca306eaa56db0
Accept: application/json
Authorization: Bearer eyJraWQiOiJjZDU1M2E4MC1kMzQ2LTRjMmEtYWQ4Mi1lMmQ5MmQxNjUyZGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc5NzkwMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzk4MjAwLCJpYXQiOjE3MzI3OTc5MDAsImp0aSI6ImE3YWNhNDZkLTYxMDctNGU3MS1hZjQ0LWZhMjYzODg5ZDQ5MSJ9.UKh_6FlW4od9IN95tc2rTcHdLW_wER1in8b2jpPnvmXzebA5wWphscvxMZGdUSAfC_VHjCqICYuFueBxca2umW4mFyoGF5JQiYGn7HqAX5pNRsjrpzbOSbvzAj5eBOaq6oKCMhkICoF25Oh0akcigpAOCCNHb3A9f-2RNDo82uhjNkwVqmMw2XAuu5NurFuXb8L97Ds4Hegxqg1bcSZlttDkJaJZYEhsEF-TyfGhbqBweq6JgeZ7zSVTdlinj3eAK0yRnRhKGvV-po0fg9XvZiumUaHoOqYjYInfZ1TxMRiZpOE0UlZsoYrAZoaFfs3440LhuExHoGJ7daFnLyRY_w
